In [1]:
# Problem 1

import numpy as np

k = [10, 11, 12, 13, 14]
z = np.zeros(25)

z[0] = 10
z[6] = 11
z[12] = 12
z[18] = 13
z[24] = 14

print(z)


[10.  0.  0.  0.  0.  0. 11.  0.  0.  0.  0.  0. 12.  0.  0.  0.  0.  0.
 13.  0.  0.  0.  0.  0. 14.]


In [2]:
import numpy as np

a = []
b = []

L = int(input("Enter the length of the arrays"))

print("Enter first array elements")
for i in range(0, L):
    value = int(input())
    a.append(value)

print("Enter second array elements")
for i in range(0, L):
    value = int(input())
    b.append(value)

A = np.array(a)
B = np.array(b)

print("Array A ==", A, "\nArray B ==", B)
# Returns True if arrays are equal, False if arrays are not equal
print(np.array_equal(A, B))



# Generating Random arrays
A = np.random.randint(1,10,size=(1,5))
B = np.random.randint(1,10,size=(1,5))
print("Array A ==", A, "\nArray B ==", B)
# Returns True if arrays are equal, False if arrays are not equal
print(np.array_equal(A, B))



Enter the length of the arrays6
Enter first array elements
1
2
3
4
5
6
Enter second array elements
9
8
7
6
5
0
Array A == [1 2 3 4 5 6] 
Array B == [9 8 7 6 5 0]
False
Array A == [[9 8 5 9 5]] 
Array B == [[4 5 9 3 9]]
False


In [3]:
# Problem 3

import numpy as np

print(0 * np.nan)
print(np.nan != np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
True
False
nan
False


In [4]:
# Problem 4

import pandas as pd
import numpy as np

ser = pd.Series(['amrita', 'school', 'of', 'engineering', 'chennai', 'campus'])
newSeries = ser.map(lambda x: x[0].upper() + x[1:-1] + x[-1])

print(ser)
print(newSeries)

a = np.array(newSeries)
print(*a, sep= ' ')


0         amrita
1         school
2             of
3    engineering
4        chennai
5         campus
dtype: object
0         Amrita
1         School
2             Of
3    Engineering
4        Chennai
5         Campus
dtype: object
Amrita School Of Engineering Chennai Campus


In [5]:
# Problem 5

import numpy as np

# Addition of arrays
A = np.array([9, 2, 7])
B = np.array([2, 5, 4])

print("1st array : ", A)
print("2nd array : ", B)

result = np.add(A, B)
print("Sum of the above arrays is : ", result)

# Multiplication of Matrices
# 2D arrays
m1 = np.array([[1, 4, 7], [2, 5, 8]])
m2 = np.array([[1, 4], [2, 5], [3, 6]])
print("\nm1:", m1, "\n\nm2:", m2)
m3 = np.dot(m1, m2)
print("\nm1*m2 =", m3)

# 3D arrays
m1 = ([1, 6, 5], [3, 4, 8], [2, 12, 3])
m2 = ([3, 4, 6], [5, 6, 7], [6, 56, 7])
print("\nm1:", m1, "\n\nm2:", m2)
m3 = np.dot(m1, m2)
print("\nm1*m2 =", m3)

1st array :  [9 2 7]
2nd array :  [2 5 4]
Sum of the above arrays is :  [11  7 11]

m1: [[1 4 7]
 [2 5 8]] 

m2: [[1 4]
 [2 5]
 [3 6]]

m1*m2 = [[30 66]
 [36 81]]

m1: ([1, 6, 5], [3, 4, 8], [2, 12, 3]) 

m2: ([3, 4, 6], [5, 6, 7], [6, 56, 7])

m1*m2 = [[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
